//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string ReferenceNo { get; set; }
        public double Quantity { get; set; }
        public double unitPrice { get; set; }
        public Nullable<double> Discountitem { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<double> otherCharges { get; set; }
        public Nullable<double> DiscountOnAll { get; set; }
        public Nullable<double> Totalamountw { get; set; }
        public string Note { get; set; }
        public double Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentNote { get; set; }
        public int CustomerID { get; set; }
        public int ItemID { get; set; }
        public int UserID { get; set; }
    }
}
