//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Sales = new HashSet<Sale>();
            this.purchases = new HashSet<purchase>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string ExpiryDate { get; set; }
        public string Barcode { get; set; }
        public string Description { get; set; }
        public string image { get; set; }
        public double price { get; set; }
        public double tax { get; set; }
        public double salesPrice { get; set; }
        public string Stock { get; set; }
        public int categoryID { get; set; }
        public int BrandID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
    }
}
