//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Barcode { get; set; }
        public string Description { get; set; }
        public string image { get; set; }
        public double price { get; set; }
        public double tax { get; set; }
        public double salesPrice { get; set; }
        public string Stock { get; set; }
        public int categoryID { get; set; }
        public int BrandID { get; set; }
    }
}
