//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string status { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> DiscountItem { get; set; }
        public Nullable<double> otherCharges { get; set; }
        public Nullable<double> DiscountonAll { get; set; }
        public double Quantity { get; set; }
        public string Note { get; set; }
        public double amount { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<double> totalAmountwdis { get; set; }
        public Nullable<double> totalAmountAll { get; set; }
        public int SupplierID { get; set; }
        public int UserID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
