//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int ID { get; set; }
        public string status { get; set; }
        public string ReferenceNo { get; set; }
        public string Date { get; set; }
        public Nullable<double> otherCharges { get; set; }
        public string otherChargesType { get; set; }
        public Nullable<double> otherChargeswithTax { get; set; }
        public Nullable<double> DiscountonAll { get; set; }
        public string DiscountOnAllType { get; set; }
        public Nullable<double> DiscountCalculate { get; set; }
        public string NoteDiscount { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string SubTotal { get; set; }
        public string GrandTotal { get; set; }
        public Nullable<double> amount { get; set; }
        public string paymentMethod { get; set; }
        public string AmountNote { get; set; }
        public int SupplierID { get; set; }
        public int UserID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual PurchaseItem PurchaseItem { get; set; }
    }
}
