//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int ItemPurchaseID { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public int PurchaseID { get; set; }
    
        public virtual purchase purchase { get; set; }
    }
}
